# Generated by Django 5.2.15 on 2026-07-06 16:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacoteContratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(default=datetime.date.today)),
                ('qtd_total', models.PositiveSmallIntegerField(default=4)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_compra', models.DateField(default=datetime.date.today)),
                ('validade', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacotes', to='core.pet')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacotes', to='core.servico')),
            ],
        ),
    ]
