# Generated by Django 5.2.15 on 2026-07-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pacotecontratado'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pacotecontratado',
            constraint=models.UniqueConstraint(fields=('pet', 'competencia'), name='unique_pacote_pet_competencia'),
        ),
    ]
