# Generated by Django 5.2.15 on 2026-07-06 17:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pacotecontratado_unique_pacote_pet_competencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('horario', models.TimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transporte', models.BooleanField(default=False)),
                ('transporte_valor', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('Liberado', 'Liberado'), ('Pendente', 'Pendente'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pacote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='core.pacotecontratado')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='core.pet')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='core.servico')),
            ],
        ),
    ]
