# Generated by Django 5.2.15 on 2026-07-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_custo_retirada_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='manejo_especial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servico',
            name='preco_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço para pet grande (acima de 15 kg). Vazio usa o preço do pequeno.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='preco_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço para pet médio (10 a 15 kg). Vazio usa o preço do pequeno.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='porte',
            field=models.CharField(blank=True, choices=[('P', 'Pequeno (até 10 kg)'), ('M', 'Médio (10 a 15 kg)'), ('G', 'Grande (acima de 15 kg)')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco_padrao',
            field=models.DecimalField(decimal_places=2, help_text='Preço para pet pequeno (até 10 kg).', max_digits=8),
        ),
    ]
