# Generated by Django 5.2.15 on 2026-07-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_atendimento_manejo_especial_servico_preco_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='agressivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='otite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='problema_pele',
            field=models.BooleanField(default=False),
        ),
    ]
